### ISSUE TITLE
Convert player to server

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-player-vlc#10]
Use a new architecture, where the server contacts the player

Need to have a handshake between server and player, ideas:
- player needs to ensure it is reachable from outside (when server is located on another network);
- player contact server as client;
- player displays his address and authentication information (maybe as a QR code) to be sent to server to configure player.

The server contacts the player each time a status request is issued by a client. (with cached response to avoid spamming the player).

Find a way for the player to be aware of the playlist.

**Comment by Neraste** [comment]
> player needs to ensure it is reachable from outside (when server is located on another network);

Maybe use uPnP.

> Find a way for the player to be aware of the playlist.

This could be easily done through WebSockets, but it is way too painful to use with Django. Meanwhile, the player can still poll the server (so it would have a mixed client/server behavior).

**Comment by Neraste** [comment]
Using websockets on the player makes this feature a bit less needy.

**Comment by Neraste** [comment]
Websockets makes this feature not needed anymore (see #40).
