### ISSUE TITLE
Unable to exit player under windows

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-player-vlc#38]
When running the player under windows, 
after the vlc player is started, it can't be exited with ctrl-c

**Comment by Neraste** [comment]
This problem is a tough one for us: the different behavior with Linux is due to the way Ctrl-C is handled on Windows. Please read this discussion on the [Python dev mailing list](https://mail.python.org/pipermail/python-dev/2017-August/148795.html).
