### ISSUE TITLE
VLC 3 Windows compatibility

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-player-vlc#39]
Vlc 3 for Windows does not include libvlc.dll and thus does not seams to work with dakara-player

**Comment by Nadeflore** [comment]
Upgrading to the latest version of python-vlc might solve the issue.
Will try this and report.

**Comment by Neraste** [comment]
This sounds more like a python-vlc issue.

**Comment by Nadeflore** [comment]
Ok, this has nothing to do with vlc 3 but with 64 bit version of vlc

In order to work with vlc 64 bit, you need a 64 bit python interpreter

See https://github.com/oaubert/python-vlc/issues/11

Closing this issue
